// <auto-generated />
using System;
using Group5Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group5Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260419151822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Group5Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "american.png",
                            Name = "American Airlines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "delta.png",
                            Name = "Delta"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "united.png",
                            Name = "United"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "southwest.png",
                            Name = "Southwest"
                        });
                });

            modelBuilder.Entity("Group5Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirlineImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 737-800",
                            AirlineId = 1,
                            AirlineImage = "american.png",
                            AirlineName = "American Airlines",
                            ArrivalTime = new DateTime(2026, 4, 21, 10, 15, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 21, 8, 0, 0, 0, DateTimeKind.Local),
                            Emission = 120.5,
                            FlightCode = "AA101",
                            From = "Chicago",
                            Price = 189.00m,
                            To = "New York"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Boeing 737 MAX 8",
                            AirlineId = 1,
                            AirlineImage = "american.png",
                            AirlineName = "American Airlines",
                            ArrivalTime = new DateTime(2026, 4, 22, 12, 30, 0, 0, DateTimeKind.Local),
                            CabinType = "Business",
                            Date = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 22, 10, 0, 0, 0, DateTimeKind.Local),
                            Emission = 210.0,
                            FlightCode = "AA215",
                            From = "Chicago",
                            Price = 499.00m,
                            To = "Los Angeles"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Airbus A320",
                            AirlineId = 2,
                            AirlineImage = "delta.png",
                            AirlineName = "Delta",
                            ArrivalTime = new DateTime(2026, 4, 21, 16, 10, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 21, 14, 0, 0, 0, DateTimeKind.Local),
                            Emission = 98.299999999999997,
                            FlightCode = "DL330",
                            From = "New York",
                            Price = 245.00m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Airbus A321",
                            AirlineId = 2,
                            AirlineImage = "delta.png",
                            AirlineName = "Delta",
                            ArrivalTime = new DateTime(2026, 4, 23, 12, 45, 0, 0, DateTimeKind.Local),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 23, 7, 0, 0, 0, DateTimeKind.Local),
                            Emission = 310.0,
                            FlightCode = "DL441",
                            From = "Los Angeles",
                            Price = 139.00m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Boeing 737-700",
                            AirlineId = 3,
                            AirlineImage = "united.png",
                            AirlineName = "United",
                            ArrivalTime = new DateTime(2026, 4, 24, 12, 30, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 24, 9, 0, 0, 0, DateTimeKind.Local),
                            Emission = 175.19999999999999,
                            FlightCode = "UA552",
                            From = "Chicago",
                            Price = 215.00m,
                            To = "Miami"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "Boeing 737 MAX 9",
                            AirlineId = 3,
                            AirlineImage = "united.png",
                            AirlineName = "United",
                            ArrivalTime = new DateTime(2026, 4, 22, 15, 55, 0, 0, DateTimeKind.Local),
                            CabinType = "Business",
                            Date = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 22, 13, 0, 0, 0, DateTimeKind.Local),
                            Emission = 88.0,
                            FlightCode = "UA663",
                            From = "Miami",
                            Price = 389.00m,
                            To = "New York"
                        },
                        new
                        {
                            FlightId = 7,
                            AircraftType = "Boeing 737-800",
                            AirlineId = 4,
                            AirlineImage = "southwest.png",
                            AirlineName = "Southwest",
                            ArrivalTime = new DateTime(2026, 4, 21, 9, 15, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 21, 6, 30, 0, 0, DateTimeKind.Local),
                            Emission = 142.69999999999999,
                            FlightCode = "WN774",
                            From = "Dallas",
                            Price = 159.00m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 8,
                            AircraftType = "Boeing 737 MAX 8",
                            AirlineId = 4,
                            AirlineImage = "southwest.png",
                            AirlineName = "Southwest",
                            ArrivalTime = new DateTime(2026, 4, 25, 19, 5, 0, 0, DateTimeKind.Local),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 25, 16, 0, 0, 0, DateTimeKind.Local),
                            Emission = 148.0,
                            FlightCode = "WN885",
                            From = "Chicago",
                            Price = 178.00m,
                            To = "Dallas"
                        },
                        new
                        {
                            FlightId = 9,
                            AircraftType = "Airbus A319",
                            AirlineId = 1,
                            AirlineImage = "american.png",
                            AirlineName = "American Airlines",
                            ArrivalTime = new DateTime(2026, 4, 23, 13, 40, 0, 0, DateTimeKind.Local),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 23, 11, 0, 0, 0, DateTimeKind.Local),
                            Emission = 77.5,
                            FlightCode = "AA323",
                            From = "New York",
                            Price = 119.00m,
                            To = "Miami"
                        },
                        new
                        {
                            FlightId = 10,
                            AircraftType = "Airbus A321neo",
                            AirlineId = 2,
                            AirlineImage = "delta.png",
                            AirlineName = "Delta",
                            ArrivalTime = new DateTime(2026, 4, 26, 11, 15, 0, 0, DateTimeKind.Local),
                            CabinType = "Business",
                            Date = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DepartureTime = new DateTime(2026, 4, 26, 8, 30, 0, 0, DateTimeKind.Local),
                            Emission = 265.0,
                            FlightCode = "DL997",
                            From = "Miami",
                            Price = 549.00m,
                            To = "Los Angeles"
                        });
                });

            modelBuilder.Entity("Group5Flight.Models.Flight", b =>
                {
                    b.HasOne("Group5Flight.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });
#pragma warning restore 612, 618
        }
    }
}
